# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

#services:
#    app.form.type.shipping:
#      class: TMTG\DatabaseBundle\Form\DailyLoggerForm
     # arguments:
    #    - '%shipping_options%'
    #  tags:
     #   - { name: form.type }
     #   -
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
